version: "3"

services:
  db:
    image: redis:latest
    container_name: db
    ports:
      - "10001:6379"
    volumes:
      - "./dbdata:/data"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  testdb:
    image: redis:latest
    container_name: testdb
    ports:
      - "10003:6379"
    volumes:
      - "./testdata:/data"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  rq:
    build: .
    container_name: rq
    ports:
      - "10002:5000"
    command: ["rq", "worker", "-u", "redis://testdb:6379/0"]
volumes:
  testdata:
  dbdata:
