version: "3"

services:
  testdb:
    image: redis/redis-stack:latest
    ports:
      - "10002:6379"
      - "10003:8001"
    volumes:
      - "testdata:/data"
    container_name: testdb
  db:
    image: redis/redis-stack-server:latest
    ports:
      - "10001:6379"
    volumes:
      - "dbdata:/data"
    container_name: redis
volumes:
  testdata:
  dbdata:
