version: "3"

services:
  testdb:
    image: redis:latest
    container_name: testdb
    ports:
      - "10003:6379"
    volumes:
      - "./testdata:/data"
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  db:
    image: redis:latest
    container_name: db
    ports:
      - "10001:6379"
    volumes:
      - "./dbdata:/data"
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
volumes:
  testdata:
  dbdata:
