version: "3"

services:
  testdb:
    image: redis/redis-stack:latest
    ports:
      - "10003:6379"
      - "10004:8001"
    volumes:
      - "./testdata:/data"
    container_name: testdb
  db:
    image: redis/redis-stack:latest
    ports:
      - "10001:6379"
      - "10002:8001"
    volumes:
      - "./dbdata:/data"
    container_name: db
volumes:
  testdata:
  dbdata:
